In [1]:
#Importing the packages - ML
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
# import warnings
# warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
#Installing the tensorflow
!pip install tensorflow

In [2]:
# Importing packages - DL
import tensorflow as tf
from tensorflow import keras

In [3]:
# checking the version of tensorflow
tf.__version__

'2.11.0'

In [4]:
#Loading the dataset
from sklearn.datasets import load_boston

In [5]:
X , y = load_boston(return_X_y = True)

C:\Users\sarwa\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [6]:
print(X.shape)
print(y.shape)

(506, 13)
(506,)


In [7]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [8]:
# Converting the X from array to dataframe
X = pd.DataFrame(X)
X.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [9]:
y 

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [10]:
# Converting the Y from array to dataframe
y = pd.DataFrame(y)
y.head()

0
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [11]:
# Feature Scaling
sc = StandardScaler()
sc_x = sc.fit_transform(X)
sc_x

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [12]:
# Scaled X to a data frame
X = pd.DataFrame(sc_x)
X.head()

0         1         2         3         4         5         6   \
0 -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1 -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2 -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3 -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4 -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   

         7         8         9         10        11        12  
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501

In [13]:
#Splitting the data to training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X, y , train_size=0.75 , random_state=101)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(379, 13)
(127, 13)
(379, 1)
(127, 1)


# Deep Learning Model
# Multilayer Perceptron(MLP)

In [14]:
# API -----> There are 2 types of API's
# Sequential (Connected layer by layer)
# Functional (Connected to any layer randomly)

In [15]:
DNN = tf.keras.models.Sequential()

In [16]:
# Input data connecting with First Hidden layer (L1)
DNN.add(tf.keras.layers.Dense(units=6 , activation= 'relu'))

In [17]:
# Input data connecting with Second Hidden layer (L2)
DNN.add(tf.keras.layers.Dense(units=6 , activation= 'relu'))

In [18]:
# Adding a Output layer
DNN.add(tf.keras.layers.Dense(units=1))

In [19]:
# Apply Optimization Techinques
# GD , SGD, Mini-batch SGD , SGD with momentum , Adagrade, adadelta, RMSProp,Adam
# Apply measured values using weights

DNN.compile(optimizer="adam", loss='mean_squared_error')

In [20]:
# Applying the input dataset along Backpropogation method
DNN.fit(X_train , y_train , batch_size=32 , epochs=500) # Batch size---> Sending the data into 32 batches ,
# epoch---> 1 Forward and 1 Backward propogation is epoch now totaly this will work for 500 times

Epoch 1/500
12/12 [==============================] - 2s 7ms/step - loss: 570.5835
Epoch 2/500
12/12 [==============================] - 0s 6ms/step - loss: 564.2448
Epoch 3/500
12/12 [==============================] - 0s 4ms/step - loss: 557.6165
Epoch 4/500
12/12 [==============================] - 0s 3ms/step - loss: 550.4007
Epoch 5/500
12/12 [==============================] - 0s 3ms/step - loss: 542.6425
Epoch 6/500
12/12 [==============================] - 0s 3ms/step - loss: 534.2099
Epoch 7/500
12/12 [==============================] - 0s 3ms/step - loss: 525.1810
Epoch 8/500
12/12 [==============================] - 0s 2ms/step - loss: 515.6469
Epoch 9/500
12/12 [==============================] - 0s 3ms/step - loss: 505.5085
Epoch 10/500
12/12 [==============================] - 0s 2ms/step - loss: 494.9828
Epoch 11/500
12/12 [==============================] - 0s 3ms/step - loss: 483.7355
Epoch 12/500
12/12 [==============================] - 0s 2ms/step - loss: 472.1567
Epoch 13/500


12/12 [==============================] - 0s 3ms/step - loss: 16.3664
Epoch 101/500
12/12 [==============================] - 0s 2ms/step - loss: 16.2098
Epoch 102/500
12/12 [==============================] - 0s 3ms/step - loss: 16.0841
Epoch 103/500
12/12 [==============================] - 0s 2ms/step - loss: 15.9624
Epoch 104/500
12/12 [==============================] - 0s 2ms/step - loss: 15.8235
Epoch 105/500
12/12 [==============================] - 0s 2ms/step - loss: 15.7272
Epoch 106/500
12/12 [==============================] - 0s 2ms/step - loss: 15.5916
Epoch 107/500
12/12 [==============================] - 0s 2ms/step - loss: 15.4947
Epoch 108/500
12/12 [==============================] - 0s 2ms/step - loss: 15.3753
Epoch 109/500
12/12 [==============================] - 0s 2ms/step - loss: 15.2757
Epoch 110/500
12/12 [==============================] - 0s 2ms/step - loss: 15.2626
Epoch 111/500
12/12 [==============================] - 0s 1ms/step - loss: 15.0634
Epoch 112/500
12/1

12/12 [==============================] - 0s 2ms/step - loss: 11.1889
Epoch 199/500
12/12 [==============================] - 0s 2ms/step - loss: 11.1569
Epoch 200/500
12/12 [==============================] - 0s 3ms/step - loss: 11.1567
Epoch 201/500
12/12 [==============================] - 0s 3ms/step - loss: 11.0913
Epoch 202/500
12/12 [==============================] - 0s 3ms/step - loss: 11.0783
Epoch 203/500
12/12 [==============================] - 0s 2ms/step - loss: 11.0346
Epoch 204/500
12/12 [==============================] - 0s 3ms/step - loss: 10.9788
Epoch 205/500
12/12 [==============================] - 0s 3ms/step - loss: 10.9886
Epoch 206/500
12/12 [==============================] - 0s 2ms/step - loss: 10.9401
Epoch 207/500
12/12 [==============================] - 0s 3ms/step - loss: 10.9078
Epoch 208/500
12/12 [==============================] - 0s 2ms/step - loss: 10.8843
Epoch 209/500
12/12 [==============================] - 0s 3ms/step - loss: 10.8983
Epoch 210/500
12/1

12/12 [==============================] - 0s 2ms/step - loss: 9.2199
Epoch 298/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1904
Epoch 299/500
12/12 [==============================] - 0s 2ms/step - loss: 9.2524
Epoch 300/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1956
Epoch 301/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1701
Epoch 302/500
12/12 [==============================] - 0s 3ms/step - loss: 9.1667
Epoch 303/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1802
Epoch 304/500
12/12 [==============================] - 0s 3ms/step - loss: 9.1631
Epoch 305/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1327
Epoch 306/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1370
Epoch 307/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1294
Epoch 308/500
12/12 [==============================] - 0s 2ms/step - loss: 9.0921
Epoch 309/500
12/12 [=========

12/12 [==============================] - 0s 2ms/step - loss: 8.5008
Epoch 398/500
12/12 [==============================] - 0s 2ms/step - loss: 8.5589
Epoch 399/500
12/12 [==============================] - 0s 2ms/step - loss: 8.4778
Epoch 400/500
12/12 [==============================] - 0s 3ms/step - loss: 8.4892
Epoch 401/500
12/12 [==============================] - 0s 2ms/step - loss: 8.4692
Epoch 402/500
12/12 [==============================] - 0s 3ms/step - loss: 8.4786
Epoch 403/500
12/12 [==============================] - 0s 2ms/step - loss: 8.4581
Epoch 404/500
12/12 [==============================] - 0s 3ms/step - loss: 8.4694
Epoch 405/500
12/12 [==============================] - 0s 3ms/step - loss: 8.4643
Epoch 406/500
12/12 [==============================] - 0s 2ms/step - loss: 8.4539
Epoch 407/500
12/12 [==============================] - 0s 1ms/step - loss: 8.4525
Epoch 408/500
12/12 [==============================] - 0s 3ms/step - loss: 8.4292
Epoch 409/500
12/12 [=========

12/12 [==============================] - 0s 2ms/step - loss: 8.0752
Epoch 498/500
12/12 [==============================] - 0s 2ms/step - loss: 7.9806
Epoch 499/500
12/12 [==============================] - 0s 2ms/step - loss: 8.0272
Epoch 500/500
12/12 [==============================] - 0s 3ms/step - loss: 8.0408


In [21]:
DNN.fit(X_train , y_train , batch_size=32 , epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9993
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 8.0194
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 7.9917
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 7.9828
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9654
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9659
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 7.9573
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 7.9544
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 8.0437
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9284
Epoch 11/100
12/12 [==============================] - 0s 3ms/step - loss: 7.9462
Epoch 12/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9369
Epoch 13/100
12/12 [=================

### Tensorflow Visual Practice

https://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=4,2&seed=0.34296&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false

In [22]:
# Predict test data with training models
y_pred = DNN.predict(X_test)
print(y_pred)

4/4 [==============================] - 0s 2ms/step
[[46.387047 ]
 [29.870142 ]
 [14.791247 ]
 [13.570076 ]
 [29.165916 ]
 [34.68506  ]
 [48.618076 ]
 [15.729773 ]
 [33.850876 ]
 [ 6.6386743]
 [25.694254 ]
 [14.082165 ]
 [17.549131 ]
 [22.71628  ]
 [22.055542 ]
 [23.613613 ]
 [ 9.861093 ]
 [32.094025 ]
 [27.72156  ]
 [24.198544 ]
 [12.460554 ]
 [22.222664 ]
 [19.768036 ]
 [30.509312 ]
 [35.13475  ]
 [16.836712 ]
 [27.112295 ]
 [18.457487 ]
 [36.095367 ]
 [35.083282 ]
 [19.708147 ]
 [17.9483   ]
 [39.305992 ]
 [45.06707  ]
 [32.525154 ]
 [22.227535 ]
 [15.325017 ]
 [15.521876 ]
 [ 4.9375625]
 [28.89604  ]
 [22.77943  ]
 [21.756763 ]
 [41.141426 ]
 [15.779757 ]
 [18.795862 ]
 [22.787659 ]
 [30.722221 ]
 [15.409834 ]
 [24.073423 ]
 [26.75019  ]
 [33.32963  ]
 [47.45641  ]
 [20.091938 ]
 [18.495213 ]
 [30.435516 ]
 [ 8.611538 ]
 [18.66498  ]
 [18.909489 ]
 [22.895718 ]
 [23.19923  ]
 [32.619728 ]
 [ 7.434262 ]
 [34.12059  ]
 [25.428896 ]
 [11.581377 ]
 [25.07946  ]
 [22.801395 ]
 [19.239439